[workspace]
authors = ["James Carron"]
channels = ["conda-forge"]
name = "EE_Calculator"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
build = "python src/build_page.py"
test = "python test/run_all.py"
setup-em = "python tools/setup_openems.py"

[dependencies]
# 3.11 because that is what the openEMS v0.0.36 Windows wheels are built for
python = "3.11.*"
