[workspace]
authors = ["James Carron"]
channels = ["conda-forge"]
name = "EE_Calculator"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
build = "python build_page.py"

[dependencies]
python = "3.12.*"
